name: synthetic-carehome-competing-risk
channels:
  - conda-forge
dependencies:
  - python>=3.9
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - scikit-survival
  - lifelines
  - xgboost
  - matplotlib
  - pytorch
  - openpyxl
  - xlsxwriter
  - jupyter
  - pytest
  - r-base
  - r-survival
  - r-cmprsk
  - pip
  - pip:
      - pycox==0.3.0
      - torchtuples==0.2.2
